### ISSUE TITLE
1. 서비스 구성하기

### ISSUE THREAD

**Issue by brainbackdoor** [next-step/infra-subway#1]
#### * 미션 진행 후에 아래 질문의 답을 Comment로 남겨주세요

1. 구성한 망의 서브넷 대역을 알려주세요

2. 배포한 서비스의 공인 IP(혹은 URL)를 알려주세요

3. 베스천 서버에 접속을 위한 pem키는 저에게 DM으로 공유해주세요

**Comment by vsh123** [comment]
1. 192.10.25.0/24
2. http://shakevan.kro.kr:443/ (ssl적용은 아직 안했습니당)
3.

**Comment by ohtaeg** [comment]
1. 192.168.252.0/24
2. http://52.79.167.90:80
http://ohtaeg.tk:80 
(SSL 적용을 어떻게 해야할지 몰라 우선 80포트를 열어놨습니다 😭 )
3. DM으로 공유드리겠습니다 :)

AWS 사용이 이번이 처음인데 많이 어렵네요 흑흑
퀴즈는 강의 전에 제출하도록 하겠습니다 🙇 
항상 감사합니다 👍

**Comment by oeeen** [comment]
1. 192.168.1.0/24
2. https://nextstep-oeeen.p-e.kr/
3. 

443으로 들어오는 요청을 nginx 단에서 8080으로 돌렸는데 정적파일들을 못받아오는 건지 뭔가 설정을 잘못해서 resource를 못받아오는데 다음에 다시 시도하도록 하겠습니다.

항상 도움을 주셔서 감사합니다. 👍

**Comment by nokchax** [comment]
1. 192.5.10.0/24
2. http://nokchax.kro.kr
3. DM으로 공유드렸습니다.

ssl적용은 하지 않고 80포트를 추가적으로 열어뒀습니다.
감사합니다 :)

**Comment by fistkim101** [comment]
1. 192.168.5.0/24
2. http://fistkim.kro.kr/
3. DM 드렸습니다.

ssl적용이 막혀서 80포트를 추가로 열어뒀습니다.
감사합니다.

**Comment by mook1594** [comment]
1. 192.20.0.0/24
2. http://mook1594.kro.kr/
(SSL 인증서 까지 받고 적용해보려고했는데, LB에다가만 적용해봐서 ec2에서 직접 적용하는 방법은 잘 모르겠네요 ㅜ)
찾아보니 이러한 방빕이 있는데, 이대로 진행하면 되는걸까요?
( https://docs.aws.amazon.com/ko_kr/AWSEC2/latest/UserGuide/SSL-on-amazon-linux-2.html )
3. DM으로 공유 드렸습니다.

**Comment by woowahanCU** [comment]
@mook1594 @fistkim101 @nokchax @ohtaeg

TLS 는 다음 미션 진행하면서 적용해보시고, 안되면 DM 남겨주세요~

**Comment by woowahanCU** [comment]
@oeeen 
nginx에서 혹시 아래와 같이 설정하셨을까요?

```
  server {
    listen 443;
    return 301 http://$host$request_uri;
  }
```

iptables 설정으로 포트포워딩을 활용해서도 한번 해결해보시겠어요?
아래 강의 자료 내용 중 Port forwarding 부분 보고 해보시면 될거 같아요 

> https://edu.nextstep.camp/s/IpGaKSMq/ls/0FmkFHov

**Comment by woowahanCU** [comment]
제출하신 분들 VPC 구성요소를 보았는데, 대부분 잘해주셨네요.
관리망을 별도로 구성하도록 미션을 안내했지만, 현재 구조에서는 외부망에 포함시켜도 대동소이한거 같긴하네요.

진행하느라 고생 많으셨어요~ 

---

이번 미션과 관련해서 질문 주신 내용들 중 몇가지 공유해요~

1. 퍼블릭IPv4 DNS 와 관련해서 문의 주신 분이 있었는데요.
   퍼블릭IPv4 DNS 정보는 활용도가 낮다고 생각해요. 보통 Public IP는 Elastic IP로 설정하고 이를 외부 DNS 혹은 Route 53 등으로 설정하여 쓰고 있어요.
   저 DNS hostname은 IP와 결합도가 높아서 활용하기는 어려운거 같아요.
   저 설정은 VPC 페이지에서 DNS hostname 설정해주면 되는데요.
   아래 링크 참고해보셔요~
   > https://galid1.tistory.com/353

---

2. profile bashrc bash_profile 차이는 무엇이고 어떤 기준으로 파일들을 나누나요?
   > http://www.solipsys.co.uk/new/BashInitialisationFiles.html
   일반적으로 home 디렉터리에 있는 저 세가지 설정 후에 bashrc 가 로딩되는걸로 알고 있어요

   > https://unix.stackexchange.com/questions/129143/what-is-the-purpose-of-bashrc-and-how-does-it-work
   bashrc는 bash쉘로 interactive 하게 운영하기 위해서 사용하는 설정이고 그러다 보니 alias 등의 설정을 넣어둔다고 설명하네요
   반면 profile은 로그인 쉘을 위한 설정이다보니 ..환경변수 등의 설정을 넣어둔다고 하네요.

**Comment by palmseung** [comment]
1. 192.7.7.0/24
2. palmseung-stations.p-e.kr/
3. DM 으로 공유드렸습니다.

[참고]
- 퀴즈는 오늘 (4/1 목) 안으로 제출하겠습니당
- tls 미적용 상태입니다. 대신에 palmseung-ec2-web 인스턴스의 80 port를 열어놓았습니다. 
- 과제 부분 중에 아래 부분이 이해가 잘 가지 않아서, scp 명령어를 이용해 pem키를 bastion server의 홈 디렉토리에 복사해두고 web인스턴스/db인스턴스에 ssh로 접속했습니다. 아래 부분에 대해서는 조금 더 찾아본 후에도 이해가 안 되면 DM드리겠습니당
<img width="1003" alt="스크린샷 2021-04-01 오전 1 25 07" src="https://user-images.githubusercontent.com/54796671/113178064-27bffb00-9289-11eb-8e70-92a09ae6638a.png">

**Comment by mindock** [comment]
1. 192.0.0.0/24
2. http://mindock-subway.kro.kr/
3. 내일 오전에 DM으로 전달드리겠습니다.

다음 미션 진행하면서 ssl 적용 진행해보겠습니다.

**Comment by sk1737030** [comment]
1. 192.30.0.0/24
2. [dongguri.kro.kr](http://dongguri.kro.kr/)
3. 늦은시간이라 내일 DM 드리겠습니다.


아 실습중에 잘 안된부분이있는데
인바운드 규칙중에 설정 중 문제가 있었습니다.

### 
 외부망
 전체 대역 : 443 포트 오픈 
 관리망 : 22번 포트 오픈
### 
망구성 문제중 관리망 설정에 대해서인데요

관리망(sk1737030-bastion) -> 외부망(sk1737030-web) 접근하기 위해 외부망에 22번 포트를 관리망의 보안 그룹으로 지정을 하고 관리망에서 외부망 ssh 접근을 했는데 timeout이 발생하더라구요.. 
이 부분을 못 해결해서 그냥 단순히 관리망 외부 ip를 22번으로 열어 주었는데  

혹시 제가 놓친 다른 설정이 있을까요?


개인적으로 이번 주는 너무 바빴었네요ㅠㅠ 지금부터라도 열심히 가보겠습니다.

**Comment by wooyongha** [comment]
1. 192.168.10.0/24
2. https://yh-line.o-r.kr
3. DM 으로 전달 드리겠습니다.

**Comment by palmseung** [comment]
과제 중에 이해가 안 갔던 아래 부분이 드디어(!) 이해가 갔습니다!!! 🤩
생활코딩에 리눅스 부분을 들으면서 보강했더니 이해가 가네요. 조금 느리지만 이어서 계속해서 과제 수행하도록 하겠습니당~


<img alt="스크린샷 2021-04-01 오전 1 25 07" width="1003" src="https://user-images.githubusercontent.com/54796671/113178064-27bffb00-9289-11eb-8e70-92a09ae6638a.png">

**Comment by woowahanCU** [comment]
@palmseung 
다행이네요! 혹시 어떤 강의였나요??

**Comment by palmseung** [comment]
@woowahanCU 
아래 링크 추가하였습니다. 리눅스쪽은 지식이 많이 부족한 탓에 생활코딩 <리눅스> 강좌 전체가 도움이 되었구요, 그중에 제가 막혔던 부분에 특히나 도움되었던 부분에 대한 링크도 추가로 기재하였습니당 

**[링크]**

- 생활코딩 <리눅스> 강의 전체 : [링크](https://www.youtube.com/playlist?list=PLuHgQVnccGMBT57a9dvEtd6OuWpugF9SH) 
- 생활코딩 <리눅스> 강좌에서 SSH와 RSA 관련 부분 : [링크](https://www.youtube.com/watch?v=BlXM5VSw95M&list=PLuHgQVnccGMBT57a9dvEtd6OuWpugF9SH&index=64)
