### ISSUE TITLE
8. 클러스터 운영하기

### ISSUE THREAD

**Issue by brainbackdoor** [next-step/infra-subway#12]
* 미션 진행 후에 아래 질문의 답을 Comment로 남겨주세요
1. kibana 링크를 알려주세요
2. grafana 링크를 알려주세요
3. 지하철 노선도는 어느정도로 requests를 설정하는게 적절한가요?
4. t3.large로 구성할 경우 Node의 LimitRange, ResourceQuota는 어느정도로 설정하는게 적절한가요?
5. 부하테스트를 고려해볼 때 Pod은 몇대정도로 구성해두는게 좋다고 생각하나요?

**Comment by nokchax** [comment]
### 1. kibana 링크를 알려주세요
  - http://kibana.nokchax.kro.kr
### 2. grafana 링크를 알려주세요
  - http://grafana.nokchax.kro.kr
### 3. 지하철 노선도는 어느정도로 requests를 설정하는게 적절한가요?
  - 그동안 진행했던 부하테스트 결과, 한 노드당 Pod수는 5개 정도가 적당했으며, 이를 바탕으로 t3.large 리소스를 나누면
    - cpu: 2 * 0.75 / 5 = 300m
    - mem: 7Gi - 2Gi / 5 = 1000Mi
    - cpu 와 mem에 여유를 좀 두었습니다. 이렇게 하는게 맞는지 모르겠네요
### 4. t3.large로 구성할 경우 Node의 LimitRange, ResourceQuota는 어느정도로 설정하는게 적절한가요?
  - 제 경우에는 pod별 300m, 1000Mi 로 설정하고 맥시멈 20대 까지 생각해뒀기 때문에
  - LimitRange는 Pod에 대한 설정이므로 300m, 1000Mi
  - ResourceQuota는 프로젝트에 대한 설정이므로 300m * 20 = 6000m, 1000Mi * 20 = 20Gi 로 두었습니다.
### 5. 부하테스트를 고려해볼 때 Pod은 몇대정도로 구성해두는게 좋다고 생각하나요?
  - 평소에는 5대 정도로도 동접자 700 ~ 800정도는 커버가 가능하였고.
  - 목표로 하고 진행했던 2000 동접자를 기준으로 평소에는 20대 정도면 커버가 가능해 보였습니다.
  - 따라서 HPA를 두어 min 5대, max 20대 까지 설정하고, 오토스케일링으로 대응하는게 좋아보입니다.

정답은 없겠지만, 이상한 부분이 있다면 피드백 부탁드립니다 🙏 
감사합니다 :)
