### ISSUE TITLE
2. 서비스 배포하기

### ISSUE THREAD

**Issue by brainbackdoor** [next-step/infra-subway#2]
#### * 미션 진행 후에 아래 질문의 답을 Comment로 남겨주세요

1. TLS가 적용된 URL을 알려주세요

2. Github Action URL을 알려주세요

3. docker hub URL을 알려주세요

4. 추가미션을 진행한 경우, github URL을 알려주세요

**Comment by nokchax** [comment]
1. https://nokchax.kro.kr
2. https://github.com/nokchax/infra-subway/actions
3. https://hub.docker.com/repository/docker/nokchax/infra-subway
4. https://github.com/nokchax/infra-subway

action쪽에서 많이 헤맸네요, 감사합니다 :)

**Comment by vsh123** [comment]
1. https://shakevan.kro.kr
2. https://github.com/vsh123/infra-subway/actions (https://github.com/vsh123/infra-subway/blob/main/.github/workflows/docker-ci.yml)
3. https://hub.docker.com/repository/docker/vsh123/infra-subway
4. 따로 커밋을 이쁘게 만들지는 않았네요ㅠㅠ

**Comment by fistkim101** [comment]
1. https://fistkim.kro.kr/
2. https://github.com/fistkim101/infra-subway/actions
3. https://hub.docker.com/repository/docker/fistkim101/infra-subway
4. https://github.com/fistkim101/infra-subway

처음 제출때 db 연결을 잘못한 부분이 있어 수정하였습니다.

Dockerfile의 entrypoint를 ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=prod", "/subway.jar"] 로 설정하여
이미지 run시에 profile을 prod로 시작되도록 설정 했고, application-prod.properties 에 db 커넥션 정보 설정하여
내부망에 붙도록 했습니다.

감사합니다.

**Comment by mook1594** [comment]
1. [https://mook1594.kro.kr/](https://mook1594.kro.kr/)
2. [https://github.com/mook1594/infra-subway/actions](https://github.com/mook1594/infra-subway/actions)
3. [https://hub.docker.com/repository/docker/wjdanr89/infra-subway](https://hub.docker.com/repository/docker/wjdanr89/infra-subway)
4. [https://github.com/mook1594/infra-subway](https://github.com/mook1594/infra-subway)

삽질의 연속 이었지만 재미있었습니다
감사합니다~ :)

**Comment by ohtaeg** [comment]
1. https://ohtaeg.tk
2. 진행중
3. 진행중
4. 진행중

현재 Reverse Proxy 설정(+TLS), 운영 DB와 애플리케이션을 연결, 테이블 스키마 버전 관리까지
완료한 상태입니다. 여유 있을 때 github action 설정 후 docker build하여 hub에 업로드 하도록 해보겠습니다 ㅠㅠ

**Comment by oeeen** [comment]
1. https://nextstep-oeeen.p-e.kr/
2. https://github.com/oeeen/infra-subway/actions
3. https://hub.docker.com/repository/docker/oeeen/infra-subway
4. 아직 못했습니다.

dockerhub에 푸시한 이미지로 어플리케이션을 띄우고 싶은데, 이게 잘 안되네요 ㅠㅠ

**Comment by mindock** [comment]
1. https://mindock-subway.kro.kr/
2. https://github.com/mindock/infra-subway/actions
3. https://hub.docker.com/repository/docker/mindock96/infra-subway
4. 추가 미션은 하지 못했습니다. 😢 

docker에 대한 이해가 부족했고, 자잘한 이슈들이 많아 시간이 오래 걸렸습니다.
그래도 미션 진행하고 나니 뿌듯하네요!! 😄 
감사합니다~

**Comment by brainbackdoor** [comment]
@oeeen 
도커 허브에 띄운 이미지가 실행할 때 어느 부분에서 실패하나요?

**Comment by brainbackdoor** [comment]
다들 github action 미션을 잘 수행해주셨네요~ 👀

**Comment by sk1737030** [comment]
1. http://dongguri.kro.kr/
2.https://github.com/sk1737030/infra-subway/actions
3. https://hub.docker.com/repository/docker/sk1737030/infra-subway
4. https://github.com/sk1737030/infra-subway 못햇지만 틈틈이 할려고 하고있습니다.

하루하루 뿌듯하네요 ㅎㅎ 감사합니다

**Comment by oeeen** [comment]
@brainbackdoor 
flyway 연결과 관련해서 문제가 좀 있는데, flyway를 false로 해도 문제가 있고.. 이것 저것 해봤는데 문제가 좀 있더라구요! 여기 빠져있기에는 시간이 너무 부족해서 다른 미션부터 해결하고 하려구요!

**Comment by wooyongha** [comment]
1. https://yh-line.o-r.kr/
2. https://github.com/wooyongha/infra-subway/actions
3. https://hub.docker.com/repository/docker/wyh951753/infra-subway
