### ISSUE TITLE
3. 서비스 운영하기

### ISSUE THREAD

**Issue by brainbackdoor** [next-step/infra-subway#3]
#### * 미션 진행 후에 아래 질문의 답을 Comment로 남겨주세요

1. 각 서버내 로깅 경로를 알려주세요

2. 추가미션을 진행한 경우, Cloudwatch 대시보드 URL을 알려주세요

**Comment by nokchax** [comment]
1. 로깅 경로
   - nginx -> /var/log/nginx
   - app -> /var/log/app
2. [nokchax-dashboard](https://ap-northeast-2.console.aws.amazon.com/cloudwatch/home?region=ap-northeast-2#dashboards:name=nokchax-dashboard)

이상하게 action에서 buildx 수행시 503 에러가나네요..
일단 nginx, app 단에만 로그를 추가해서 두개만 남겼습니다. 감사합니다 :)

**Comment by fistkim101** [comment]
1. 로깅경로
nginx : /var/log/nginx
app : /home/ubuntu/nextstep/log

2. [fistkim101 Cloudwatch](https://ap-northeast-2.console.aws.amazon.com/cloudwatch/home?region=ap-northeast-2#dashboards:name=fistkim101-dashboard)

이번 미션도 재미있었습니다.
감사합니다.

**Comment by vsh123** [comment]
1. nginx : /varlog/subway/nginx
   app : /var/log/subway/
2. [shakevan](https://ap-northeast-2.console.aws.amazon.com/cloudwatch/home?region=ap-northeast-2#dashboards:name=shakevan-dashboard)

**Comment by brainbackdoor** [comment]
@vsh123 대시보드에 아무것도 없어요~ (혹시 저장을 안하신건..)

@fistkim101 재밌게 해주셔서 감사합니다~

**Comment by sk1737030** [comment]
1. nginx: /var/log/nginx
   app: /var/log/next-step/
2. [sk1737030 ](https://ap-northeast-2.console.aws.amazon.com/cloudwatch/home?region=ap-northeast-2#dashboards:name=sk1737030-dashboard)

환경별 로그 설정에서 해맸네요.
감사합니다!

**Comment by mindock** [comment]
1. nginx: /var/log/nginx
    app: /var/log/subway
2. [mindock-dashboard](https://ap-northeast-2.console.aws.amazon.com/cloudwatch/home?region=ap-northeast-2#dashboards:name=mindock-dashboard)

**Comment by oeeen** [comment]
1. nginx: /var/log/nginx
    app: /var/log/subway
2. [oeeen-dashboard](https://ap-northeast-2.console.aws.amazon.com/cloudwatch/home?region=ap-northeast-2#dashboards:name=oeeen-dashboard)

logback 설정에서 헤맸네요.. 공부할 게 많네요 ㅎㅎ 감사합니다.

**Comment by Qualson-JM** [comment]
1. nginx: /var/log/nginx
app: /var/log/app

2. [mook1594-dashboard](https://ap-northeast-2.console.aws.amazon.com/cloudwatch/home?region=ap-northeast-2#dashboards:name=mook1594-dashboard)

**Comment by wooyongha** [comment]
1. nginx: /var/log/nginx
   app: /var/log/app

2. [wooyongha-dashboard](https://ap-northeast-2.console.aws.amazon.com/cloudwatch/home?region=ap-northeast-2#dashboards:name=wooyongha-dashboard)
